api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "product-bundle"
type = "function"
uid = "ea53565e-4301-3b4b-4328-d39f9dac2ec80d0136b5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"